version: "3.3"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    working_dir: /app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./api:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env
    # networks:
    #   - my-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    working_dir: /app
    restart: always
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    # networks:
    #   - my-network

volumes:
  pgdata:
# networks:
#   my-network:
#     driver: bridge
